name: flutter_audio_service_demo
description: Companion project for tutorial on audio_service plugin.
publish_to: 'none'

version: 3.0.4+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  interval_tree: ^0.4.1

dependencies:
  platform: ^3.1.0 
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.3
  audio_video_progress_bar: ^2.0.3
  get_it: ^8.0.3
  just_audio: ^0.9.27
  #just_audio_libwinmedia: ^0.0.4+1
  just_audio_windows: ^0.2.2
  audio_service: ^0.18.6
  http: ^1.3.0
  path_provider: ^2.0.0
  archive: ^4.0.2
  blinking_text: ^1.0.4
  url_launcher: ^6.1.2
  item_selector: ^0.2.0
  animated_text_kit: ^4.2.2
  file_manager: ^1.0.0
  awesome_snackbar_content:
  catcher:
    path: ../catcher

  fluttertoast: ^8.2.12
  provider: ^6.0.1
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  shared_preferences: ^2.0.0
  audioplayers: ^5.2.1  # Downgrade to a compatible version
  audioplayers_darwin: ^5.0.2  # Specify compatible version
  
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - images/vasis.jpeg
    - images/k.png
    - images/km.png
    - images/kmt.png
    - images/appicon.png

flutter_icons:
  android: true
  ios: true
  macos: true
  image_path: "images/appicon.png"
  adaptive_icon_foreground: "images/appicon.png"    
