name: flutter_audio_service_demo
description: Companion project for tutorial on audio_service plugin.
publish_to: 'none'

version: 2.1.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0 
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.2
  audio_video_progress_bar: ^0.5.0
  get_it: ^7.1.2
  just_audio: ^0.9.27
  #just_audio_libwinmedia: ^0.0.4+1
  just_audio_windows: ^0.1.0
  audio_service: ^0.18.6
  http: ^0.13.0
  path_provider: ^2.0.0
  archive: ^3.0.0
  blinking_text: ^0.0.4+1
  url_launcher: ^6.1.2
  item_selector: ^0.2.0
  animated_text_kit: ^4.2.2
  file_manager: ^1.0.0
  awesome_snackbar_content:
  catcher: ^0.6.9
  fluttertoast: ^8.0.7
  audioplayers: ^0.19.1
  
 
dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - images/vasis.jpeg
    - images/k.png
    - images/km.png
    - images/kmt.png
    - images/appicon.png

flutter_icons:
  android: true
  ios: true
  macos: true
  image_path: "images/appicon.png"
  adaptive_icon_foreground: "images/appicon.png"    
